services:
  postgres:
    image: postgres:18
    container_name: conecta-tech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: conecta_tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: